### ISSUE TITLE
Todo alerts

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2713]
- [x] Fix interface and network to use the new API
- [x] Display errors when an alert callback fails
- [x] Remove stateless alert release logic based on alert_tstamp_end (it does now work with new logic)
- [x] Rework gui threshold gui
- [x] Fix interface alert counter
- [x] Handle delete alerts on the Alertable from gui
- [x] p2p threshold cross: should use the p2p category
- [x] Change database alert_periodicity to alert_granularity
- [x] Fix alertsDashboard / flow explorer
- [x] Fix syn flood alerts
- [x] Fix alerts on remote hosts
- [x] Release alerts on Alertable (e.g. host) when it becomes idle
- [x] Release alerts during shutdown
- [x] Count sqlite dropped alerts due to queue full
- [x] Remove old api `alerts_api:trigger` and rename `alerts_api:new_trigger` in `alerts_api:trigger`
- [x] Unify alert notification format with alert format
- [x] Unify queues alert format
- [x] Convert all the alert messages to JSON

**Comment by emanuele-f** [comment]
Implemented
